services:
  - type: web
    name: relay-server
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python relay_server.py
    env: python
    autoDeploy: true
    region: oregon
    disk:
      name: relay
      mountPath: /data
      sizeGB: 1
    envVars: []
